Detailed explanation is done in notebook

In [3]:
import tensorflow as tf

In [6]:
model=tf.keras.Sequential()
model.add(tf.keras.layers.SimpleRNN(units=3,input_shape=(3,5)))   #Three input words ("movie was good") and 5 length vector as in example page 11
model.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

In [7]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 3)                 27        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.get_weights()[0]  # page 11 (input layer to hidden layer)

array([[ 0.33788854, -0.4610704 ,  0.60250944],
       [ 0.2803312 , -0.28501672, -0.21757877],
       [ 0.8113597 ,  0.5813704 , -0.56180656],
       [-0.69645464,  0.53151375,  0.40111643],
       [ 0.4233318 ,  0.7870415 , -0.5842741 ]], dtype=float32)

In [10]:
model.get_weights()[1] # page 12

array([[ 0.3624364 , -0.8913297 ,  0.27234384],
       [ 0.85256296,  0.43512493,  0.28948689],
       [-0.37653187,  0.12726969,  0.9176199 ]], dtype=float32)

In [11]:
model.get_weights()[2] #page 11 output layer

array([0., 0., 0.], dtype=float32)